name: 🚀 Register Speckit
description: Register your speckit to awesome-spec-kits registry
title: "[Register] "
labels: ["registration"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📦 Register or Update Your Speckit
        
        Our bot will automatically:
        1. ✅ Validate your speckit
        2. ✅ Extract metadata from pyproject.toml
        3. ✅ Create a PR to add or update it in the registry
        
        **For New Registration**:
        - Valid `pyproject.toml` with required fields (name, version, description)
        - README.md with documentation
        - Open source license (MIT, Apache, BSD, etc.)
        - Working CLI commands
        
        **For Updates**:
        - Simply submit the same repository URL again
        - The bot will automatically detect and update your existing entry
        - Update `version`, `description`, `tags`, or other metadata in your `pyproject.toml` first

  - type: input
    id: repository
    attributes:
      label: GitHub Repository
      description: Your speckit's GitHub repository URL
      placeholder: https://github.com/ACNet-AI/MetaSpec
    validations:
      required: true

  - type: input
    id: pypi
    attributes:
      label: PyPI Package Name (Optional)
      description: Package name on PyPI if published
      placeholder: meta-spec

  - type: textarea
    id: highlights
    attributes:
      label: Key Features (Optional)
      description: Brief highlight of your speckit's main features (3-5 points)
      placeholder: |
        - Feature 1
        - Feature 2
        - Feature 3

  - type: markdown
    attributes:
      value: |
        ## 🤖 Automated Validation
        
        After you submit this issue, the bot will automatically verify:
        - ✅ Valid `pyproject.toml` (name, version, description)
        - ✅ `README.md` exists with adequate documentation
        - ✅ CLI commands defined in `[project.scripts]`
        - ✅ Open source license present
        
        **You don't need to manually verify these - the bot handles it!**
        
        If any requirement is missing, the bot will comment with:
        - Clear error messages
        - What's missing
        - How to fix it

  - type: checkboxes
    id: authorization
    attributes:
      label: Authorization & Confirmation
      options:
        - label: I am the maintainer or have permission to register/update this speckit
          required: true

  - type: checkboxes
    id: optional-self-check
    attributes:
      label: Optional Self-Check (Bot will verify these)
      description: These are optional - the bot will validate them after submission
      options:
        - label: I have verified my speckit meets the technical requirements
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **What happens next?**
        
        After you submit this issue:
        1. Our bot will validate your speckit
        2. If valid, a PR will be automatically created (new registration or update)
        3. Maintainers will review and merge the PR
        4. Your speckit will appear in (or be updated in) the registry!
        
        If validation fails, the bot will comment with details on what needs to be fixed.

